// Generated by CoffeeScript 2.1.0
(function() {
  var HelloWorld;

  HelloWorld = class HelloWorld {
    hello(name = "World") {
      return `Hello, ${name}!`;
    }

  };

  module.exports = HelloWorld;

}).call(this);
